# -*- coding: utf-8 -*-
"""mizaç testi

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1OFDP7ludWWCASDUPdxD-RQkE5WRltES1
"""

!pip install gradio

import gradio as gr
print("Gradio başarıyla yüklendi!")

import gradio as gr
import math

###############################################################################
# 1) Her tip için detaylı açıklama (temel pozitif/negatif duygu, kanat vb.)
###############################################################################
study_tips = {
    1: """**Tip 1 (Mükemmeliyetçi)**

- **Temel Pozitif Duygusu:** Düzen, doğruluk, mükemmellik hissi
- **Temel Negatif Duygusu:** Hata yapma korkusu
- **Öne Çıkan Yeteneği:** Planlama ve sistem kurma
- **Temel Problemi:** Aşırı eleştirel yaklaşım
- **İç Sesi (Aktif Ses):** "Daha iyi olmalıyım, hata yapmamalıyım."
- **Bilgiye Bakışı:** Kurallı, ilkelere dayalı bilgiler
- **Okula Bakışı:** Disiplinli, kuralcı bir yer
- **Konsantrasyonu Azaltan:** Düzensizlik, belirsizlik
- **Konsantrasyonu Artıran:** Net kurallar, planlama
- **Onu Motive Eden Şeyler:** Takdir, doğruyu yapma isteği
- **Çalışma Alışkanlıkları:** Düzenli, liste yaparak çalışır
- **Sorumluluk Algısı:** Görev bilinci yüksek

- **Kanat Etkisinde (Eylemsel / Duygusal / Bilişsel):**
  - (1) 9 veya 2 kanadı ağır basıyorsa, daha sakin veya yardımsever yönler öne çıkar.
""",

    2: """**Tip 2 (Yardımsever)**

- **Temel Pozitif Duygusu:** Sevildiğini ve faydalı olduğunu hissetme
- **Temel Negatif Duygusu:** Sevilmeme veya değersizlik korkusu
- **Öne Çıkan Yeteneği:** Empati, başkalarına destek olma
- **Temel Problemi:** Kendi ihtiyaçlarını ihmal etme
- **İç Sesi (Aktif Ses):** "İnsanlara yardım etmeliyim."
- **Bilgiye Bakışı:** İnsani ve duygusal boyutu ön planda
- **Okula Bakışı:** Sosyal ve paylaşımcı bir ortam beklentisi
- **Konsantrasyonu Azaltan:** Soğuk ilişkiler, çatışma ortamı
- **Konsantrasyonu Artıran:** Destekleyici, sıcak arkadaşlık
- **Onu Motive Eden Şeyler:** Takdir görmek, yardım edebilmek
- **Çalışma Alışkanlıkları:** Grup çalışmalarına yatkın
- **Sorumluluk Algısı:** Başkalarına yardım etmeyi sorumluluk sayar

- **Kanat Etkisinde (Eylemsel / Duygusal / Bilişsel):**
  - (2) 1 veya 3 kanadına kayarak daha düzenli veya başarı odaklı hale gelebilir.
""",

    3: """**Tip 3 (Başaran)**

- **Temel Pozitif Duygusu:** Başarı ve takdir edilme isteği
- **Temel Negatif Duygusu:** Yetersizlik veya başarısızlık korkusu
- **Öne Çıkan Yeteneği:** Hedef koyma, yüksek motivasyon
- **Temel Problemi:** Kendini aşırı başarıya endeksleme
- **İç Sesi (Aktif Ses):** "Başarmalıyım, en iyi olmalıyım."
- **Bilgiye Bakışı:** Faydalı ve sonuç odaklı bilgiyi önemser
- **Okula Bakışı:** Rekabetçi, başarıların öne çıktığı yer
- **Konsantrasyonu Azaltan:** Belirsiz hedefler, monotonluk
- **Konsantrasyonu Artıran:** Net hedefler, performans ölçütleri
- **Onu Motive Eden Şeyler:** Ödül, başarı hissi, alkışlanmak
- **Çalışma Alışkanlıkları:** Verimli, hızla sonuca odaklanır
- **Sorumluluk Algısı:** Görevlerini başarı fırsatı olarak görür

- **Kanat Etkisinde (Eylemsel / Duygusal / Bilişsel):**
  - (3) 2 veya 4’e kayarak daha yardımsever veya daha yaratıcı yön alabilir.
""",

    4: """**Tip 4 (Bireyci)**

- **Temel Pozitif Duygusu:** Özgünlük, derinlik, farklı olma hissi
- **Temel Negatif Duygusu:** Eksiklik, değer görmeme korkusu
- **Öne Çıkan Yeteneği:** Yaratıcılık, estetik duyarlılık
- **Temel Problemi:** Duygusal dalgalanmalar
- **İç Sesi (Aktif Ses):** "Özgün olmalıyım, farklıyım."
- **Bilgiye Bakışı:** Sanatsal, duygusal ve derinlikli bilgiye odaklı
- **Okula Bakışı:** Kendini ifade edebileceği ortam olmalı
- **Konsantrasyonu Azaltan:** Sıradanlık, yüzeysellik
- **Konsantrasyonu Artıran:** Yaratıcı çalışmalar, özgün projeler
- **Onu Motive Eden Şeyler:** Farklılık, özel hissetme
- **Çalışma Alışkanlıkları:** İlham odaklı, yoğun duygusal dalgalarla çalışır
- **Sorumluluk Algısı:** Bazen duygusal haller sorumluluğu aksatabilir

- **Kanat Etkisinde (Eylemsel / Duygusal / Bilişsel):**
  - (4) 3 veya 5’e kayarak daha başarı veya araştırma odaklı hale gelebilir.
""",

    5: """**Tip 5 (Araştırmacı)**

- **Temel Pozitif Duygusu:** Merak, bilgiyle güçlenme
- **Temel Negatif Duygusu:** Yetersiz veya bilgisiz kalma korkusu
- **Öne Çıkan Yeteneği:** Analitik düşünme, araştırma
- **Temel Problemi:** Sosyal izolasyon, aşırı entelektüel yaklaşım
- **İç Sesi (Aktif Ses):** "Daha fazla bilgi edinmeliyim."
- **Bilgiye Bakışı:** Derinlemesine analiz, entelektüel merak
- **Okula Bakışı:** Bilgi edinmek için fırsat gözüyle bakar
- **Konsantrasyonu Azaltan:** Aşırı sosyal talep, gürültü
- **Konsantrasyonu Artıran:** Sessiz ortam, bol kaynak
- **Onu Motive Eden Şeyler:** Yeni keşifler, derin araştırma
- **Çalışma Alışkanlıkları:** Kendi başına, yoğun odaklanma
- **Sorumluluk Algısı:** Bilgi odaklı sorumluluk üstlenir

- **Kanat Etkisinde (Eylemsel / Duygusal / Bilişsel):**
  - (5) 4 veya 6’ya kayarak daha yaratıcı veya daha güven arayışlı yön öne çıkabilir.
""",

    6: """**Tip 6 (Sadık)**

- **Temel Pozitif Duygusu:** Güven, ait olma hissi
- **Temel Negatif Duygusu:** Kaygı, güvensizlik korkusu
- **Öne Çıkan Yeteneği:** Sorumluluk, sadakat, risk analizi
- **Temel Problemi:** Kararsızlık, endişe
- **İç Sesi (Aktif Ses):** "Dikkatli olmalıyım, güvende miyim?"
- **Bilgiye Bakışı:** Güvenilir kaynak ve doğrulanmış bilgiye önem verir
- **Okula Bakışı:** Kuralları ve net yönergeleri olan bir yer ister
- **Konsantrasyonu Azaltan:** Belirsizlik, baskı altında hissetme
- **Konsantrasyonu Artıran:** Destekleyici ortam, net yönergeler
- **Onu Motive Eden Şeyler:** Güven ve onay görmek
- **Çalışma Alışkanlıkları:** Çoğu zaman grup veya rehber arar
- **Sorumluluk Algısı:** Sadakatle yerine getirir

- **Kanat Etkisinde (Eylemsel / Duygusal / Bilişsel):**
  - (6) 5 veya 7’ye kayarak daha analitik veya daha keyif odaklı hale gelebilir.
""",

    7: """**Tip 7 (Maceracı)**

- **Temel Pozitif Duygusu:** Eğlence, merak, yeni deneyimler
- **Temel Negatif Duygusu:** Sıkılma, kısıtlanma korkusu
- **Öne Çıkan Yeteneği:** Yenilik arayışı, pozitiflik, adaptasyon
- **Temel Problemi:** Derinleşememe, yüzeysellik, çabuk sıkılma
- **İç Sesi (Aktif Ses):** "Hep yeni bir şey bulmalıyım."
- **Bilgiye Bakışı:** Çeşitli ve ilginç bilgilere açık
- **Okula Bakışı:** Sosyal ve eğlenceli etkinlikler bekler
- **Konsantrasyonu Azaltan:** Tekdüze, uzun süreli zorunluluklar
- **Konsantrasyonu Artıran:** Renkli, farklı, interaktif öğrenme
- **Onu Motive Eden Şeyler:** Özgürlük, yenilik, macera
- **Çalışma Alışkanlıkları:** Parça parça çalışır, farklı konuları aynı anda alabilir
- **Sorumluluk Algısı:** Rutin sorumluluklardan çabuk sıkılabilir

- **Kanat Etkisinde (Eylemsel / Duygusal / Bilişsel):**
  - (7) 6 veya 8’e kayarak daha güven arayan veya daha lider/kararlı yön kazanabilir.
""",

    8: """**Tip 8 (Meydan Okuyan)**

- **Temel Pozitif Duygusu:** Güç, kontrol, adalet sağlama
- **Temel Negatif Duygusu:** Zayıf düşme, kontrol kaybı korkusu
- **Öne Çıkan Yeteneği:** Liderlik, cesaret, koruyuculuk
- **Temel Problemi:** Aşırı sertlik, baskın tavır
- **İç Sesi (Aktif Ses):** "Güçlü olmalıyım, kontrol bende olmalı."
- **Bilgiye Bakışı:** Pratik ve stratejik bilgiyi önemser
- **Okula Bakışı:** Yetkili veya lider pozisyonda olmak isteyebilir
- **Konsantrasyonu Azaltan:** Haksızlık, otoriteyle çatışma
- **Konsantrasyonu Artıran:** Net hedefler, rekabet
- **Onu Motive Eden Şeyler:** Güçlü olmak, adaleti sağlamak
- **Çalışma Alışkanlıkları:** Hızlı karar verir, diretir
- **Sorumluluk Algısı:** Koruyuculuk, liderlik algısı yüksek

- **Kanat Etkisinde (Eylemsel / Duygusal / Bilişsel):**
  - (8) 7 veya 9’a kayarak daha neşeli veya daha uzlaşmacı hale gelebilir.
""",

    9: """**Tip 9 (Barışçı)**

- **Temel Pozitif Duygusu:** Huzur, uyum, sakinlik
- **Temel Negatif Duygusu:** Çatışma, gerginlik korkusu
- **Öne Çıkan Yeteneği:** Uzlaştırma, empati
- **Temel Problemi:** Kendi ihtiyaçlarını yok sayma
- **İç Sesi (Aktif Ses):** "Rahat ve huzurlu olmalıyım."
- **Bilgiye Bakışı:** Çatışmasız, sakin şekilde öğrenmeyi tercih eder
- **Okula Bakışı:** Sakin, stressiz bir ortam
- **Konsantrasyonu Azaltan:** Gerginlik, yüksek tempo
- **Konsantrasyonu Artıran:** Yumuşak geçişler, huzurlu atmosfer
- **Onu Motive Eden Şeyler:** Destekleyici çevre, barışçıl ilişkiler
- **Çalışma Alışkanlıkları:** Kendi temposunda, acele etmeden çalışır
- **Sorumluluk Algısı:** Uyumluluk adına sorumluluk alır

- **Kanat Etkisinde (Eylemsel / Duygusal / Bilişsel):**
  - (9) 8 veya 1’e kayarak daha lider veya daha mükemmeliyetçi yön gösterebilir.
"""
}

###############################################################################
# 3) Kod: Tam %100 Yüzde Dağılımı, Kanat Hesabı, Boş Soru Kontrolü
###############################################################################

# 10 soruluk 'questions' listesi - eksiksiz.
questions = [
    {
        "question": "1) Bir grup çalışması yaparken nasıl davranırsın?",
        "options": {
            "A": ("Proje detaylarıyla ilgilenir, kurallara uyulmasını sağlarsın.", {1: 2, 6: 1}),
            "B": ("Arkadaşlarına yardım etmeye odaklanırsın.", {2: 2}),
            "C": ("Öne çıkıp yönlendirir, ekibi motive edersin.", {3: 2, 8: 1}),
            "D": ("Sessizce gözlem yapar, gerektiğinde fikir sunarsın.", {5: 2, 9: 1})
        }
    },
    {
        "question": "2) Okuldaki bir kulüp etkinliğinde sana en çok ne çekici gelir?",
        "options": {
            "A": ("Herkesi organize edip sorumluluk almak.", {1: 1, 8: 1}),
            "B": ("İhtiyacı olanlara yardım edebileceğin bir etkinlik.", {2: 2}),
            "C": ("Başarılı olup takdir görmek.", {3: 2}),
            "D": ("Kendini ifade edebileceğin sanatsal veya farklı bir etkinlik.", {4: 2, 7: 1})
        }
    },
    {
        "question": "3) Yeni bir şey öğrenirken kendini nasıl hissedersin?",
        "options": {
            "A": ("Meraklı ve derine inmeye hevesli.", {5: 2}),
            "B": ("Öğrendiklerimi daha çok insanla paylaşmak isterim.", {2: 1, 7: 1}),
            "C": ("Güvenli ve emin olana kadar soru sormaya devam ederim.", {6: 2}),
            "D": ("Hedefime ulaşmak için öğrenirim, sonuca odaklanırım.", {3: 1, 1: 1})
        }
    },
    {
        "question": "4) Arkadaşlarınla plan yaparken en çok neye dikkat edersin?",
        "options": {
            "A": ("Planın net ve düzenli olmasına.", {1: 1, 6: 1}),
            "B": ("Hem eğlenceli hem de değişik bir şeyler yapmaya.", {7: 2}),
            "C": ("Sessiz sakin vakit geçirebileceğimiz bir ortam bulmaya.", {9: 2}),
            "D": ("Benim ilgimi çekecek yaratıcılığa veya özgünlüğe.", {4: 2})
        }
    },
    {
        "question": "5) Seni en çok ne rahatsız eder?",
        "options": {
            "A": ("Hatalı veya düzensiz işlerin olması.", {1: 2}),
            "B": ("Sevdiğim insanların üzülmesi.", {2: 2}),
            "C": ("Başarısız olmak veya yeterince takdir görmemek.", {3: 2}),
            "D": ("Kendimi ifade edecek özgür alan bulamamam.", {4: 2, 8: 1})
        }
    },
    {
        "question": "6) Bir problemle karşılaştığında ilk tepkin nedir?",
        "options": {
            "A": ("Detayları düşünüp mantıklı bir çözüm ararım.", {5: 2, 1: 1}),
            "B": ("Endişelenip güvence aramaya çalışırım.", {6: 2}),
            "C": ("Hemen harekete geçer ya da kontrolü ele alırım.", {8: 2}),
            "D": ("Gerekirse yardım isterim, sakin kalmaya çalışırım.", {9: 2})
        }
    },
    {
        "question": "7) Başkalarıyla yaşadığın uyuşmazlıklarda nasıl davranırsın?",
        "options": {
            "A": ("Geri planda kalıp kavgadan uzak durmaya çalışırım.", {9: 2}),
            "B": ("İlk önce kendimi savunur veya karşı çıkarım.", {8: 2}),
            "C": ("Orta yolu bulmaya çalışırım.", {6: 1, 2: 1}),
            "D": ("Konuşarak ikna edebileceğime inanırım.", {3: 1, 7: 1})
        }
    },
    {
        "question": "8) Bir başarı elde ettiğinde veya övgü aldığında kendini nasıl hissedersin?",
        "options": {
            "A": ("Çok mutlu olurum, takdir görmek beni motive eder.", {3: 2, 7: 1}),
            "B": ("Bazen hak etmediğimi düşünür, daha iyisini yapmalıydım derim.", {1: 1, 4: 1}),
            "C": ("Önemli olan başkalarına yardım etmemdi, övgü ikinci planda.", {2: 2}),
            "D": ("Benim için çok da önemli değildir, huzurlu olmak yeterlidir.", {9: 2})
        }
    },
    {
        "question": "9) Farklı duyguları nasıl yaşarsın?",
        "options": {
            "A": ("Duygularımı derinden hissederim, bazen çok yoğun yaşarım.", {4: 2}),
            "B": ("Çok derine inmeden kontrol etmeye çalışırım.", {8: 1, 3: 1}),
            "C": ("Duygularımı daha çok kendi içimde yaşarım, diğerleriyle pek paylaşmam.", {5: 2}),
            "D": ("Endişe duyarsam bile bunu güvendiğim kişilerle paylaşırım.", {6: 1, 9: 1})
        }
    },
    {
        "question": "10) Tatil planı yaparken seni en çok ne heyecanlandırır?",
        "options": {
            "A": ("Rahatlamak ve hiç acele etmeden sakin zaman geçirmek.", {9: 2}),
            "B": ("Yeni yerler görüp maceraya atılmak.", {7: 2}),
            "C": ("Planlı, düzenli ve her şeyin en iyi şekilde organize olması.", {1: 2}),
            "D": ("Yanımda sevdiklerimin olması ve onlarla ilgilenmek.", {2: 2})
        }
    }
]

def distribute_100_percent(raw_percent_list):
    """Her tipin yuvarlanmış yüzdesini toplama 100 olacak şekilde düzeltir."""
    results = []
    for item in raw_percent_list:
        tip = item["tip"]
        raw = item["raw"]
        r = round(raw)
        fraction = raw - math.floor(raw)
        results.append({"tip": tip, "raw": raw, "rounded": r, "fraction": fraction})

    sum_rounded = sum(x["rounded"] for x in results)
    diff = 100 - sum_rounded

    if diff > 0:
        # fraction desc
        results.sort(key=lambda x: x["fraction"], reverse=True)
        for i in range(diff):
            results[i]["rounded"] += 1
    elif diff < 0:
        # fraction asc
        results.sort(key=lambda x: x["fraction"])
        for i in range(abs(diff)):
            if results[i]["rounded"] > 0:
                results[i]["rounded"] -= 1

    # final: 'rounded' desc
    results.sort(key=lambda x: (x["rounded"], x["tip"]), reverse=True)
    return results

def get_wing(main_type, final_list):
    """
    Ana tipin olası kanat adayları:
    - 1 için (9, 2)
    - 9 için (8, 1)
    - diğerleri (main_type-1, main_type+1)
    final_list -> [{'tip': X, 'rounded': Y}, ...] (desc)
    """
    if main_type == 1:
        candidates = [9, 2]
    elif main_type == 9:
        candidates = [8, 1]
    else:
        candidates = [main_type - 1, main_type + 1]

    found = []
    for item in final_list:
        if item["tip"] in candidates:
            found.append(item)
    if not found:
        return None
    elif len(found) == 1:
        return found[0]["tip"]
    else:
        found.sort(key=lambda x: x["rounded"], reverse=True)
        return found[0]["tip"]

def puan_hesapla_ve_oner(*answers):
    # 1) Boş sorular
    unanswered = []
    for i, ans in enumerate(answers):
        if not ans:
            unanswered.append(i+1)
    if unanswered:
        msg = "Lütfen tüm soruları cevaplayın!\n\nCevaplanmamış sorular: "
        msg += ", ".join(str(num) for num in unanswered)
        return msg

    # 2) Puan hesapla
    scores = {i: 0 for i in range(1, 10)}
    for i, ans in enumerate(answers):
        letter = ans.split(')')[0].strip()
        _, pts_dict = questions[i]["options"][letter]
        for t, p in pts_dict.items():
            scores[t] += p

    total_score = sum(scores.values())
    if total_score == 0:
        return "Puanlar 0 gibi görünüyor; hesaplama yapılamadı."

    # 3) Ham yüzde -> tam %100
    raw_list = []
    for tip_no, sc in scores.items():
        raw_p = (sc / total_score) * 100
        raw_list.append({"tip": tip_no, "raw": raw_p})
    final_list = distribute_100_percent(raw_list)

    # 4) Tüm tipleri listele
    result_text = "### Tüm Kişilik Tipleri (Tam %100 Oranlar)\n"
    for idx, item in enumerate(final_list, start=1):
        result_text += f"{idx}. **Tip {item['tip']}** - %{item['rounded']}\n"

    # Ana tip
    main_type = final_list[0]["tip"]
    result_text += f"\n---\n**En Yakın Olduğun Tip: {main_type}**\n\n"

    # Kanat
    wing_type = get_wing(main_type, final_list)
    if wing_type:
        result_text += f"Kanat etkisi: **Tip {wing_type}**\n\n"

    # Tip açıklaması (her tip tanımlı olduğu için boş kalmaz)
    tip_text = study_tips[main_type]  # 1..9 hepsi var
    result_text += tip_text
    return result_text

def build_interface():
    with gr.Blocks() as demo:
        gr.Markdown("# BİZİM İŞİMİZ EĞİTİM: MİZAÇ TESTİ")
        gr.Markdown("""
BİZİM İŞİMİZ EĞİTİM: MİZAÇ TESTİ ile başarıya giden yolda ilk adımınızı atın!
Bu test, mizaç yapınızı ortaya çıkararak öğrenme tarzınıza en uygun stratejileri belirlemenize yardımcı olacak.
Matematikte başarı artık bir hedef değil, sizin için bir gerçek olacak.
Kendinizi tanıyın, potansiyelinizi ortaya çıkarın ve matematiği kolayca fethedin.
Çünkü bizim işimiz eğitim, sizin işiniz başarı.
""")

        radio_list = []
        for idx, q in enumerate(questions, start=1):
            choice_list = []
            for letter, (desc, _) in q["options"].items():
                choice_list.append(f"{letter}) {desc}")
            radio = gr.Radio(
                label=f"Soru {idx}: {q['question']}",
                choices=choice_list,
                value=None
            )
            radio_list.append(radio)

        btn = gr.Button("Sonucu Göster")
        output_md = gr.Markdown(label="Öneriler / Kanat Etkisi")

        btn.click(fn=puan_hesapla_ve_oner, inputs=radio_list, outputs=output_md)

    return demo

# Ana çalıştırma
if __name__ == "__main__":
    demo = build_interface()
    demo.launch()